---
# handlers file for uniqconsulting.nextcloud

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload php-fpm
  service:
    name: php73-php-fpm
    state: reloaded

- name: restart php-fpm
  service:
    name: php73-php-fpm
    state: restarted

- name: restart mariadb
  service:
    name: mariadb
    state: restarted

- name: restart redis
  service:
    name: redis
    state: restarted
...
